### ISSUE TITLE
[CY-4261]     if (!strncasecmp(arg, "file://", strlen("file://")))  throws an issue

### ISSUE THREAD

**Issue by vtorri** [codacy/codacy-flawfinder#21]
https://app.codacy.com/gh/vtorri/entice/issues?categoryType=Security

Finds potential security problems in strlen calls

Does not handle strings that are not \0-terminated; if given one it may perform an over-read (it could cause a crash if unprotected) (CWE-126)

code : 

    if (!strncasecmp(arg, "file://", strlen("file://")))

but strlen("file://") is always 7 as we pass a static string which is always correctly 0-terminated

**Comment by franciscodua** [comment]
Hi @vtorri 

Codacy only integrates with Flawfinder, which is an open-source tool that looks for potential security problems (https://dwheeler.com/flawfinder/).

And it seems you have a suggestion for the tool itself and not Codacy's integration. If this is the case we suggest you open a similar issue [here](https://github.com/david-a-wheeler/flawfinder).

Let us know if I misunderstood and we can indeed help you with this problems, or if we should close this issue.

**Comment by franciscodua** [comment]
I'm closing this issue. But if you are still having issues let us know
